let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Kemeja Wanita",
    price: 45000,
    desc: "Baju",
    img: "images/img-1.jpg",
    overview: "(721)",
  },
  {
    id: "ioytrhndcv",
    name: "Kemeja Kantor",
    price: 100000,
    desc: "Baju",
    img: "images/img-2.jpg",
    overview: "(213)",
  },
  {
    id: "wuefbncxbsn",
    name: "WhiteStyle",
    price: 25000,
    desc: "Baju",
    img: "images/bajusoe2.png",
    overview: "(235)",
  },
  {
    id: "thyfhcbcv",
    name: "Celana Kotak",
    price: 300000,
    desc: "Celana",
    img: "images/celanasoe.png",
    overview: "(776)",
  },
  {
    id: "thiecbawdjksadjk",
    name: "BlackStyle",
    price: 25000,
    desc: "Baju",
    img: "images/bajusoe3.png",
    overview: "(456)",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Sepatu Kasual",
    price: 200000,
    desc: "Sepatu",
    img: "images/img-6.png",
    overview: "(789)",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Celana Pria",
    price: 450000,
    desc: "Celana",
    img: "images/celanasoe2.png",
    overview: "(565)",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Topi Pancing",
    price: 45000,
    desc: "Topi",
    img: "images/topisoe.png",
    overview: "(311)",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Jam Tangan",
    price: 85000,
    desc: "Jam",
    img: "images/jamsoe.png",
    overview: "(911)",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Celana Denim",
    price: 120000,
    desc: "Celana",
    img: "images/img-10.png",
    overview: "(112)",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Topi Kawaryuno",
    price: 35000,
    desc: "Topi",
    img: "images/img-11.png",
    overview: "(878)",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Sepatu Mlayuning",
    price: 350000,
    desc: "Sepatu",
    img: "images/sepatusoe.png",
    overview: "(666)",
  },
];
